port: 3000
elastic:
  host: 'localhost:9200'
  usersIndex: 'user'
  usersType: 'user'
  vacanciesIndex: 'vacancy'
  vacanciesType: 'vacancy'
  skillsIndex: 'skill'
  skillsType: 'skill'
  occupationIndex: 'occupation'
  occupationType: 'occupation'
  desirableTrainingsIndex: 'desirabletraining'
  desirableTrainingsType: 'desirabletraining'
  desirableTrainingLocationsIndex: 'desirabletraininglocation'
  desirableTrainingLocationsType: 'desirabletraininglocation'
  libIndex: 'location'
  locationType: 'location'
  educationTypesIndex: 'educationtype'
  educationTypesType: 'educationtype'
  educationLevelIndex: 'educationlevel'
  educationLevelType: 'educationlevel'
  formalEducationLevelIndex: 'formaleducationlevel'
  formalEducationLevelType: 'formaleducationlevel'
  languagesIndex: 'languages'
  languagesType: 'languages'
um:
  mongodbConnectionString: 'mongodb://localhost:27017/umpack'
  accessTokenSecret: 'myrandomstring'
  passwordHashSecret: 'mypasswordsecret'
  accessTokenExpiresIn: '5h'
  cookieAccessTokenName: 'accessToken'
  activateOnSignup: true
