elastic:
  host: 'localhost:9200'
  usersIndex: 'user'
  usersType: 'user'
  vacanciesIndex: 'vacancy'
  vacanciesType: 'vacancy'
  skillsIndex: 'skill'
  skillsType: 'skill'
  libIndex: 'lib'
  locationType: 'location'
  educationTypesIndex: 'educationType'
  educationTypesType: 'educationType'
  educationLevelIndex: 'educationLevel'
  educationLevelType: 'educationLevel'
