elastic:
  host: 'localhost:9200'
  usersIndex: 'user'
  usersType: 'user'
  vacanciesIndex: 'vacancy'
  vacanciesType: 'vacancy'
  skillsIndex: 'skill'
  skillsType: 'skill'
  desirableJobsIndex: 'desirablejob'
  desirableJobsType: 'desirablejob'
  libIndex: 'lib'
  locationType: 'location'
  educationTypesIndex: 'educationtype'
  educationTypesType: 'educationType'
  educationLevelIndex: 'educationlevel'
  educationLevelType: 'educationLevel'
  formalEducationLevelIndex: 'formaleducationlevel'
  formalEducationLevelType: 'formalEducationLevel'
um:
  mongodbConnectionString: 'mongodb://localhost:27017/umpack'
  accessTokenSecret: 'myrandomstring'
  passwordHashSecret: 'mypasswordsecret'
  accessTokenExpiresIn: '1h'
  cookieAccessTokenName: 'accessToken'
