port: 3000
elastic:
  host: 'localhost:9200'
  usersIndex: 'user'
  usersType: 'user'
  vacanciesIndex: 'job'
  vacanciesType: 'job'
  skillsIndex: 'skill'
  skillsType: 'skill'
  desirableJobsIndex: 'desirablejob'
  desirableJobsType: 'desirablejob'
  desirableTrainingsIndex: 'desirabletraining'
  desirableTrainingsType: 'desirabletraining'
  desirableTrainingLocationsIndex: 'desirabletraininglocation'
  desirableTrainingLocationsType: 'desirabletraininglocation'
  libIndex: 'lib'
  locationType: 'location'
  educationTypesIndex: 'educationtype'
  educationTypesType: 'educationType'
  educationLevelIndex: 'educationlevel'
  educationLevelType: 'educationLevel'
  formalEducationLevelIndex: 'formaleducationlevel'
  formalEducationLevelType: 'formalEducationLevel'
  languagesIndex: 'languages'
  languagesType: 'languages'
um:
  mongodbConnectionString: 'mongodb://localhost:27017/umpack'
  accessTokenSecret: 'myrandomstring'
  passwordHashSecret: 'mypasswordsecret'
  accessTokenExpiresIn: '1h'
  cookieAccessTokenName: 'accessToken'
  activateOnSignup: true
